steps:
  - name: 'gcr.io/$PROJECT_ID/git-lfs'
    args: ['init']
  - name: 'gcr.io/$PROJECT_ID/git-lfs'
    args: ['remote', 'add', 'origin', '[REPO_ADDRESS]']
  - name: 'gcr.io/$PROJECT_ID/git-lfs'
    args: ['fetch']
  - name: 'gcr.io/$PROJECT_ID/git-lfs'
    args: ['reset', '--soft', 'origin/$BRANCH_NAME']
  - name: 'gcr.io/$PROJECT_ID/git-lfs'
    args: ['lfs', 'pull']
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: food-for-thoughts
  _LABELS: gcb-trigger-id=294ff71c-609b-4980-96c6-b440df025960
  _TRIGGER_ID: 294ff71c-609b-4980-96c6-b440df025960
  _DEPLOY_REGION: asia-southeast1
  _GCR_HOSTNAME: asia.gcr.io
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - food-for-thoughts
